components/common.tsx, pages/getting-started.tsx, pages/learn.tsx, pages/manage-access.tsx, pages/subscribe.tsx, static_data/theme.tsx
code examples and minor other fixes
=> update on prod 

components/common.tsx, pages/manage-billing.tsx, pages/usage.tsx
1. Update usage with today's usage. 
2. Update text to reflect changes to the API output.
3. Update UsageInfoBanner to accept dynamic props and be 100% width
resolves DEL-2944
=> Update usage with today's usage, including text

components/usage.tsx, pages/home.tsx, pages/usage.tsx
Purpose
1. Separate usage details and summary into different components to make the code cleaner.
2. Implement individual error logic on each component
3. Also, remove unused component
Tests
Run against the mock server, there should be no visible difference to the user.
Related to https://speechmatics.atlassian.net/browse/DEL-3250 (as discussed)
=> separate usage summary and details + delete unused component

components/billing.tsx, components/common.tsx, pages/manage-billing.tsx
=> Add data-qa attrs to delete card modal

pages/transcribe.tsx
=> Add data-qa attrs to transcribe page

components/recent-jobs.tsx, utils/use-jobs-hook.ts
Fix errors formatting duration and empty tooltip errors.
Tested locally against Dumitru's failing data.
=> Fix tooltip errors

components/recent-jobs.tsx, pages/usage.tsx, utils/use-jobs-hook.ts
Purpose
Improve capture and display of errors when getting jobs
=> update error handling on getting jobs

components/recent-jobs.tsx
Fix button link to go to transcribe page
=> fix transcribe button

components/icons-library.tsx, components/recent-jobs.tsx, components/side-menu.tsx, utils/use-jobs-hook.ts
Fix a couple of errors relating to the handling of null and error states in the jobs response
=> fix error handling in get jobs

utils/hooks.ts, utils/use-jobs-hook.ts
Add isPolling to dependencies for useEffect in polling hook
=> fix polling use effect dependencies and remove add millisecond

components/recent-jobs.tsx, components/transcript-download-menu.tsx, components/transcription-viewer.tsx, pages/transcribe.tsx, utils/call-api.ts
Remove download audio file choice from ui
=> Del 3766 download audio fixes

components/recent-jobs.tsx
Disable the download menu for jobs in a running or rejected state
=> disable download menu when running or rejected

utils/use-jobs-hook.ts
change setJobs to use spread operator to create a new address in memory for equality comparison (javascript is bad)
=> improve polling

components/recent-jobs.tsx
Disables the menu button when the job is running or rejected
=> disable menu button

components/recent-jobs.tsx, components/transcription-viewer.tsx, utils/date-utils.tsx, utils/use-jobs-hook.ts
Alter the popup on the jobs list to be more responsive in design. Make sure it works down to 360px by 600px with download and copy button permanently visible
=> fix transcript popup responsiveness

components/recent-jobs.tsx
Fixed the loading skeleton to be responsive down to 360px width
=> loading skeleton responsiveness

components/common.tsx, components/recent-jobs.tsx, components/transcribe-form.tsx, pages/transcribe.tsx
Updates:
* Text based on https://speechmatics.atlassian.net/browse/DEL-3902
* Removes cancel job for running job https://speechmatics.atlassian.net/browse/DEL-3903
* Blocks buttons for rejected jobs (small bug, no ticket)
=> change copy, modal, rejected buttons

components/recent-jobs.tsx
Update times on jobs list
* Add banner with info on UTC usage
* Remove accidental extra time formatting
=> Update times on jobs list

components/common.tsx, pages/manage-access.tsx
Purpose
* Make it clear a key cannot be created without a name
* Change error presentation to look like rest of app
=> improve error handle + DEL-3172

components/recent-jobs.tsx
Purpose
* update jobs list data-qa tags to be outside tooltip
=> update data-qa in jobs list

utils/call-api.ts
Detect a deleted user 410 error response and log this user out to prevent them continuing to use the portal
=> DEL-3632: Logout deleted user

.gitignore, components/billing.tsx, components/common.tsx, global-setup.ts, package-lock.json, package.json, playwright.config.ts, tests/account-state.test.ts, tests/initial.test.ts, tests/jobs-list.test.ts, tests/render.test.ts, yarn.lock
- Added UI tests for 'past_due' and 'unpaid' contract states
- Added dotenv dependency to read values from .env file
=> Del 4421 add account state tests

utils/transcribe-elements.ts
Purpose
* Add the Indonesian language option
* Sort the languages correctly
=> Add Indonesian and sort languages
